id: 2c0e397509f24cecb530dc691edae190
initial_creation_type: ocr
source_metadata:
  volumes:
    ab827859370146ee8602931696d675fc:
      base_file: v059.txt
      image_group_id: I1PD95905
      title: ''
      total_pages: 1913
      volume_number: 60
